CREATE TABLE group_member (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  userId INTEGER NOT NULL,
  groupId INTEGER NOT NULL,
  status_ INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY (userId) REFERENCES user(id),
  FOREIGN KEY (groupId) REFERENCES group_(id)
);
