CREATE TABLE group (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  creator INTEGER NOT NULL,
  description TEXT,
  createdAt DATETIME NOT NULL,
  FOREIGN KEY (creator) REFERENCES user(id)
);
