// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: privateChatNotification.sql

package crud

import (
	"context"
	"time"
)

const createPrivateChatNotification = `-- name: CreatePrivateChatNotification :one
 INSERT INTO private_chat_notification (
  source_id, target_id, chat_noti, last_msg_at
) VALUES (
  ?, ?, ?, ?
)
RETURNING id, source_id, target_id, chat_noti, last_msg_at
`

type CreatePrivateChatNotificationParams struct {
	SourceID  int64
	TargetID  int64
	ChatNoti  int64
	LastMsgAt time.Time
}

func (q *Queries) CreatePrivateChatNotification(ctx context.Context, arg CreatePrivateChatNotificationParams) (PrivateChatNotification, error) {
	row := q.db.QueryRowContext(ctx, createPrivateChatNotification,
		arg.SourceID,
		arg.TargetID,
		arg.ChatNoti,
		arg.LastMsgAt,
	)
	var i PrivateChatNotification
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.TargetID,
		&i.ChatNoti,
		&i.LastMsgAt,
	)
	return i, err
}

const deletePrivateChatNotification = `-- name: DeletePrivateChatNotification :exec
DELETE FROM private_chat_notification
WHERE source_id = ? AND target_id = ?
`

type DeletePrivateChatNotificationParams struct {
	SourceID int64
	TargetID int64
}

func (q *Queries) DeletePrivateChatNotification(ctx context.Context, arg DeletePrivateChatNotificationParams) error {
	_, err := q.db.ExecContext(ctx, deletePrivateChatNotification, arg.SourceID, arg.TargetID)
	return err
}

const getPrivateChatNoti = `-- name: GetPrivateChatNoti :many
SELECT id, source_id, target_id, chat_noti, last_msg_at FROM private_chat_notification
WHERE target_id = ?
`

func (q *Queries) GetPrivateChatNoti(ctx context.Context, targetID int64) ([]PrivateChatNotification, error) {
	rows, err := q.db.QueryContext(ctx, getPrivateChatNoti, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PrivateChatNotification
	for rows.Next() {
		var i PrivateChatNotification
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.TargetID,
			&i.ChatNoti,
			&i.LastMsgAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePrivateChatNotification = `-- name: UpdatePrivateChatNotification :one
UPDATE private_chat_notification
SET chat_noti = ?,
last_msg_at = ?
WHERE source_id = ? AND target_id = ?
RETURNING id, source_id, target_id, chat_noti, last_msg_at
`

type UpdatePrivateChatNotificationParams struct {
	ChatNoti  int64
	LastMsgAt time.Time
	SourceID  int64
	TargetID  int64
}

func (q *Queries) UpdatePrivateChatNotification(ctx context.Context, arg UpdatePrivateChatNotificationParams) (PrivateChatNotification, error) {
	row := q.db.QueryRowContext(ctx, updatePrivateChatNotification,
		arg.ChatNoti,
		arg.LastMsgAt,
		arg.SourceID,
		arg.TargetID,
	)
	var i PrivateChatNotification
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.TargetID,
		&i.ChatNoti,
		&i.LastMsgAt,
	)
	return i, err
}
