// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: privateChatNotification.sql

package crud

import (
	"context"
	"time"
)

const createPrivateChatNotification = `-- name: CreatePrivateChatNotification :one
 INSERT INTO private_chat_notification (
  source_id, target_id, chat_noti, last_msg_at
) VALUES (
  ?, ?, ?, ?
)
RETURNING id, source_id, target_id, chat_noti, last_msg_at
`

type CreatePrivateChatNotificationParams struct {
	SourceID  int64
	TargetID  int64
	ChatNoti  int64
	LastMsgAt time.Time
}

func (q *Queries) CreatePrivateChatNotification(ctx context.Context, arg CreatePrivateChatNotificationParams) (PrivateChatNotification, error) {
	row := q.db.QueryRowContext(ctx, createPrivateChatNotification,
		arg.SourceID,
		arg.TargetID,
		arg.ChatNoti,
		arg.LastMsgAt,
	)
	var i PrivateChatNotification
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.TargetID,
		&i.ChatNoti,
		&i.LastMsgAt,
	)
	return i, err
}

const deletePrivateChatNotification = `-- name: DeletePrivateChatNotification :exec
DELETE FROM private_chat_notification
WHERE source_id = ? AND target_id = ?
`

type DeletePrivateChatNotificationParams struct {
	SourceID int64
	TargetID int64
}

func (q *Queries) DeletePrivateChatNotification(ctx context.Context, arg DeletePrivateChatNotificationParams) error {
	_, err := q.db.ExecContext(ctx, deletePrivateChatNotification, arg.SourceID, arg.TargetID)
	return err
}

const getPrivateChatNoti = `-- name: GetPrivateChatNoti :one
SELECT id, source_id, target_id, chat_noti, last_msg_at FROM private_chat_notification
WHERE source_id = ? AND target_id = ?
`

type GetPrivateChatNotiParams struct {
	SourceID int64
	TargetID int64
}

func (q *Queries) GetPrivateChatNoti(ctx context.Context, arg GetPrivateChatNotiParams) (PrivateChatNotification, error) {
	row := q.db.QueryRowContext(ctx, getPrivateChatNoti, arg.SourceID, arg.TargetID)
	var i PrivateChatNotification
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.TargetID,
		&i.ChatNoti,
		&i.LastMsgAt,
	)
	return i, err
}
